Add DataMet backend for Italian Radar data
openradar/xradar pull request #175
Opened 2024-06-27 18:04 UTC by wolfidan

Dear xradar people, this is a first try at adding a new backend to read the data from the Italian radars provided by Gianfranco Vulpiani that we plan to use at the open radar course at ERAD2024.

https://zenodo.org/records/4897697

I must say that I had some trouble understanding all the classes that are required to wrap it into xarray, but I tried my best and it seems to work, as I was able to read all 165 provided files. I have added some tests but they are somewhat simplistic at the moment and only test the basic reader not the wrapper to xarray (other tests seem to do the same things).

The DataMet files are not consistent in which sweep corresponds to which elevation: sometimes sweep 1 could be 16° other times 90°. I find it a bit weird but left it as is and didn't try to remap it. I wonder if this could be an issue when reading them into pyart?

Thank you for your time. 
Next week I will be in vacation and might not answer immediately, sorry about that.

- [ ] Closes https://github.com/openradar/erad2024/issues/7
- [ ] Tests added
- [ ] Changes are documented in `history.md`

2024-06-28 07:44 UTC, kmuehlbauer commented
Thanks @wolfidan! The ruff and numpy2 issues should be resolved now by #177. I'll have a closer look here later.

2024-06-28 07:49 UTC, kmuehlbauer commented on xradar/version.py
@wolfidan Please remove that file. It will be autogenerated in the build process.

2024-06-28 12:30 UTC, kmuehlbauer commented on xradar/version.py
I've removed it now. Want to see how things go.

2024-06-28 13:13 UTC, kmuehlbauer commented
@wolfidan I've taken the chance to fix this up to green CI. Looks good so far. We might just copy/adapt code/tests from the other backends to finish this.

Thanks for this nice addition!

2024-06-28 13:46 UTC, kmuehlbauer commented
This works for me with different elevations. Looks that this is a top down strategy.

```python
import open_radar_data
import xarray as xr
fname = open_radar_data.DATASETS.fetch("H-000-VOL-ILMONTE-201907100700.tar.gz")
with xr.open_dataset(fname, engine="datamet", group="sweep_8") as ds:
    display(ds)
    ds = ds.set_coords("sweep_mode")
    ds = ds.wrl.georef.georeference()
    ds.DBTH.wrl.vis.plot()
```

2024-06-29 11:52 UTC, wolfidan commented
That's amazing, thanks a lot @kmuehlbauer, I will add more tests the week after the next to increase codecov

2024-07-15 15:55 UTC, wolfidan commented
@kmuehlbauer 
All tests and codecov should be fine now. I still had an issue.

        ds = xr.open_dataset(datamet_file, engine="datamet")

doesn't work. I had to use

       ds = xr.open_dataset(datamet_file, engine=xradar.io.backends.DataMetBackendEntrypoint)

in the unit tests

Maybe you can easily fix that. I'm looking  forward to see you do this, so I can do it next time.
Thanks a lot

2024-07-16 12:40 UTC, mgrover1 requested changes
Can you try adding back in the engine="datamet" now that the linting issues have been resolved?

2024-07-16 12:40 UTC, mgrover1 commented on tests/io/test_io.py
> +        engine=xradar.io.backends.DataMetBackendEntrypoint,
```suggestion
        engine="datamet",
```

2024-07-16 12:40 UTC, mgrover1 commented on tests/io/test_io.py
> +        engine=xradar.io.backends.DataMetBackendEntrypoint,
```suggestion
        engine="datamet",
```

2024-07-16 12:40 UTC, mgrover1 commented on tests/io/test_io.py
> +        engine=xradar.io.backends.DataMetBackendEntrypoint,
```suggestion
        engine="datamet",
```

2024-07-16 12:42 UTC, kmuehlbauer requested changes
Not sure why it doesn't work for you. But you would need to install the package first before being able to use the entrypoints.

2024-07-16 12:42 UTC, kmuehlbauer commented on tests/io/test_io.py
> +        engine=xradar.io.backends.DataMetBackendEntrypoint,
```suggestion
        engine="datamet",
```

2024-07-16 12:42 UTC, kmuehlbauer commented on tests/io/test_io.py
> +        engine=xradar.io.backends.DataMetBackendEntrypoint,
```suggestion
        engine="datamet",
```

2024-07-16 12:42 UTC, kmuehlbauer commented on tests/io/test_datamet.py
> +def test_file_tyes(data):
```suggestion
def test_file_types(data):
```

2024-07-16 12:43 UTC, wolfidan commented
Thanks @mgrover1 @kmuehlbauer , I'll change it very soon and see if it passes the tests

2024-07-17 08:25 UTC, wolfidan commented
Ok I changed according to your propositions.

2024-07-17 08:32 UTC, kmuehlbauer approved these changes
Great work @wolfidan!

2024-07-17 14:55 UTC, mgrover1 approved these changes
Agreed - thanks so much for this contribution @wolfidan !!

2024-07-17 14:56 UTC, merged