ADD: MRR2 backend reattempt
openradar/xradar pull request #198
Opened 2024-08-23 16:00 UTC by rcjackson

I have restarted the pull request for the MRR2 reader using the current version as a base. I'm hoping that I've made changes that fix the PR. 
- [x] Closes #xxxx
- [x] Tests added
- [x] Changes are documented in `history.md`

2024-08-23 16:05 UTC, rcjackson commented
Ruff is failing on notebooks unrelated to this PR.

2024-08-27 06:30 UTC, kmuehlbauer commented
@rcjackson Any idea on the `bus error` at the one nexrad test?

2024-08-27 12:07 UTC, rcjackson commented
Memory leak somewhere? I haven’t been able to find it.

From: Kai Mühlbauer ***@***.***>
Date: Tuesday, August 27, 2024 at 1:30 AM
To: openradar/xradar ***@***.***>
Cc: Jackson, Robert ***@***.***>, Mention ***@***.***>
Subject: Re: [openradar/xradar] ADD: MRR2 backend reattempt (PR #198)
@ rcjackson Any idea on the bus error at the one nexrad test? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned. Message ID: <openradar/xradar/pull/198/c2311678517@ github. com>
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.

ZjQcmQRYFpfptBannerEnd

@rcjackson<https://urldefense.us/v3/__https:/github.com/rcjackson__;!!G_uCfscf7eWS!Y_ThD4cL6cHVVZFproDciAN6Zhh3zHbZjGjkBh00rdXNdZifRZTblHs3Olk6cj_ElibCJCXw1HbCk4qgArYj4Sko$> Any idea on the bus error at the one nexrad test?

—
Reply to this email directly, view it on GitHub<https://urldefense.us/v3/__https:/github.com/openradar/xradar/pull/198*issuecomment-2311678517__;Iw!!G_uCfscf7eWS!Y_ThD4cL6cHVVZFproDciAN6Zhh3zHbZjGjkBh00rdXNdZifRZTblHs3Olk6cj_ElibCJCXw1HbCk4qgAuQyKY9d$>, or unsubscribe<https://urldefense.us/v3/__https:/github.com/notifications/unsubscribe-auth/AFIQA5AQZNYZPYRKM4XHGPDZTQMIFAVCNFSM6AAAAABNAOJKR6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGMJRGY3TQNJRG4__;!!G_uCfscf7eWS!Y_ThD4cL6cHVVZFproDciAN6Zhh3zHbZjGjkBh00rdXNdZifRZTblHs3Olk6cj_ElibCJCXw1HbCk4qgAkmwPjZP$>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-08-27 13:07 UTC, kmuehlbauer requested changes
@rcjackson I've made a couple comments, how we might tackle the issue with the `bus error`.

I've checked the tests on main here:
https://github.com/openradar/xradar/actions/runs/10578167450
and they are working perfectly fine. 

So I'm assuming that the ominous `bus error` is somehow introduced with the changes in this PR, or are revealed by the changes in this PR. 

If you have any other ideas how to tackle this, please comment.

2024-08-27 13:07 UTC, kmuehlbauer commented on tests/io/test_metek.py
> +    ds = xr.open_dataset(metek_ave_gz_file, engine="metek")
Could you try using context manager here?

2024-08-27 13:07 UTC, kmuehlbauer commented on tests/io/test_metek.py
> +    ds.close()
... and remove these two lines?

2024-08-27 13:07 UTC, kmuehlbauer commented on tests/io/test_metek.py
> +    ds = None
Remove

2024-08-27 13:07 UTC, kmuehlbauer commented on tests/io/test_metek.py
> +    ds = xr.open_dataset(metek_pro_gz_file, engine="metek")
Use context manager.

2024-08-27 13:07 UTC, kmuehlbauer commented on tests/io/test_metek.py
> +    ds = None
Remove

2024-08-27 13:07 UTC, kmuehlbauer commented on tests/io/test_metek.py
> +    ds.close()
Remove two lines

2024-08-27 13:07 UTC, kmuehlbauer commented on tests/io/test_metek.py
> +    ds = None
remove

2024-08-27 13:10 UTC, kmuehlbauer commented on tests/conftest.py
> +    os.remove(fnamei)
```suggestion
```

2024-08-27 13:10 UTC, kmuehlbauer commented on tests/conftest.py
> +    os.remove(fnamei)
```suggestion
```

2024-08-27 13:10 UTC, kmuehlbauer commented on tests/conftest.py
> +    os.remove(fnamei)
```suggestion
```

2024-08-27 13:10 UTC, kmuehlbauer commented on tests/io/test_metek.py
> +    ds.close()
```suggestion
    with xr.open_dataset(metek_ave_gz_file, engine="metek") as ds:
        assert "corrected_reflectivity" in ds.variables.keys()
        assert "velocity" in ds.variables.keys()
        rainfall = ds["rainfall_rate"].isel(range=0).cumsum() / 60.0
        np.testing.assert_allclose(rainfall.values[-1], 0.938)
        np.testing.assert_allclose(ds["reflectivity"].values[0], test_arr_ave)
```

2024-08-28 16:05 UTC, rcjackson commented
@kmuehlbauer  None of the suggestions worked. I even explicitly close the datatree's Dataset to make sure the references clear, but that still doesn't seem to resolve the issue. I'll have to think of more solutions for this later, but for now I'm at a loss.

2024-08-28 16:17 UTC, kmuehlbauer commented
@rcjackson This seems like a hard nut to crack, thanks for checking this out. 

Maybe those open references are some hint as to why the error occurred in the first place? I'll have a look at our mrr reader (which is extremely fragile while being based on numpy.genfromtxt).

2024-08-28 16:24 UTC, kmuehlbauer commented
@rcjackson We might try to run this sequentially.

Please change here:

https://github.com/openradar/xradar/blob/1b4a535f582de9083debc86860010aa20cb1f98c/.github/workflows/ci.yml#L69

and remove `-n auto` from the call.

Another thing to look after is this error:

```python
  Traceback (most recent call last):
    File "/home/runner/work/xradar/xradar/xradar/io/backends/metek.py", line 447, in close
      for k in self._data.keys():
               ^^^^^^^^^^
  AttributeError: 'MRR2File' object has no attribute '_data'. Did you mean: 'data'?
```

which was issued here: https://github.com/openradar/xradar/actions/runs/10600167596/job/29376980199?pr=198

It seems, that one CI run finishes and all other raise with this error. Strange!

2024-08-28 16:35 UTC, rcjackson commented
> @rcjackson We might try to run this sequentially.
> 
> Please change here:
> 
> https://github.com/openradar/xradar/blob/1b4a535f582de9083debc86860010aa20cb1f98c/.github/workflows/ci.yml#L69
> 
> and remove `-n auto` from the call.
> 
> Another thing to look after is this error:
> 
> ```python
>   Traceback (most recent call last):
>     File "/home/runner/work/xradar/xradar/xradar/io/backends/metek.py", line 447, in close
>       for k in self._data.keys():
>                ^^^^^^^^^^
>   AttributeError: 'MRR2File' object has no attribute '_data'. Did you mean: 'data'?
> ```
> 
> which was issued here: https://github.com/openradar/xradar/actions/runs/10600167596/job/29376980199?pr=198
> 
> It seems, that one CI run finishes and all other raise with this error. Strange!

Running it sequentially seems to get it working, though slows down the testing a bit. Azure stores are typically memory limited at 1 GB, so I bet it was running in parallel and going up against the memory limit.

2024-08-28 16:41 UTC, kmuehlbauer commented
Ok, so this looks like a memory leak somewhere.

This will need some profiling, I guess.

2024-10-16 11:34 UTC, kmuehlbauer approved these changes

2024-10-16 11:34 UTC, merged